spring:
  application:
    name: task-manager-api

  datasource:
    url: jdbc:postgresql://localhost:5433/task_manager_db
    username: postgres
    password: Fran2109
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# Configuración JWT
app:
  jwt:
    secret: 7QmJrL5wXp2vZ8sN3kT9hY6bM4cF1aE0dRgU8iK7nOqHsVfWxZpYbAcDeFgHjKlMnP
    expiration: 86400000   # 24 horas en milisegundos